# CHAPTER 6 - EXERCISE 1: TRUY XUẤT CÁC PHẦN TỬ VÀ THỐNG KÊ TRÊN SERIES

## Ghi chú về dữ liệu
**Ghi chú về dữ liệu:** Major League Baseball (MLB) là giải đấu bóng chày chuyên nghiệp. Major League Baseball có tổng cộng 30 đội bóng đến từ nhiều bang khác nhau của Mỹ và Canada (29 đội từ Mỹ và 1 đội từ Canada). MLB luôn được sự quan tâm lớn của hầu hết fan bóng chày trên toàn thế giới, và cũng được xem là giải đấu nổi tiếng và uy tín nhất, tập hợp những cầu thủ có trình độ cao nhất trong bộ môn này. Dữ liệu heights (tính theo inches) và weights (tính theo pounds) là chiều cao và cân nặng của các cầu thủ có tham gia 1 số giải của MLB.

**_Đọc và chuyển dữ liệu, sau đó tính BMI theo điều kiện, truy xuất dữ liệu._**

In [1]:
import pandas as pd

In [2]:
def get_data(fname):
    f = open(fname)
    data = f.read()
    f.close()
    return list(eval(data))

**_Đọc dữ liệu từ 2 tập tin 'heights.txt' và 'weights.txt' vào list là height, weight._**

In [3]:
height = get_data('data6/heights.txt')
weight = get_data('data6/weights.txt')

### Yêu cầu 1:

**a. Tạo Series ser_height từ list height**

In [4]:
ser_height = pd.Series(height)

**b. In danh sách các phần tử của ser_height**

In [5]:
ser_height

0       74
1       74
2       72
3       72
4       73
        ..
1010    73
1011    74
1012    75
1013    75
1014    73
Length: 1015, dtype: int64

**c. Cho biết kích thước (shape) của ser_height**

In [6]:
ser_height.shape

(1015,)

**d. Cho biết kiểu dữ liệu của các phần tử trong ser_height**

In [7]:
ser_height.dtype

dtype('int64')

### Yêu cầu 2:

**a. Tạo Series ser_weight từ list weight**

In [8]:
ser_weight = pd.Series(weight) 

**b. In danh sách các phần tử của ser_weight**

In [9]:
ser_weight

0       180
1       215
2       210
3       210
4       188
       ... 
1010    190
1011    180
1012    205
1013    190
1014    195
Length: 1015, dtype: int64

**c. Cho biết kích thước (shape) của ser_weight**

In [10]:
ser_weight.shape

(1015,)

**d. Cho biết kiểu dữ liệu của các phần tử trong ser_height**

In [11]:
ser_weight.dtype

dtype('int64')

### Yêu cầu 3:

**Cho hệ số quy đổi từ inch sang m là 0.0254**

**a. Tạo Series height_m dựa trên công thức: ser_height * hệ số quy đổi, làm tròn đến 2 chữ số thập phân**

In [12]:
height_m = pd.Series(round(ser_height*0.0254,2))

**b. In danh sách các phần tử của height_m**

In [13]:
height_m

0       1.88
1       1.88
2       1.83
3       1.83
4       1.85
        ... 
1010    1.85
1011    1.88
1012    1.90
1013    1.90
1014    1.85
Length: 1015, dtype: float64

### Yêu cầu 4:

**Cho hệ số quy đổi từ pound sang kg là 0.453592**

**a. Tạo Series weight_kg dựa trên công thức: ser_weight * hệ số quy đổi Làm tròn đến hàng đơn vị**

In [14]:
weight_kg = pd.Series(round(ser_weight*0.453592))

**b. In danh sách các phần tử của weight_kg**

In [15]:
weight_kg

0       82.0
1       98.0
2       95.0
3       95.0
4       85.0
        ... 
1010    86.0
1011    82.0
1012    93.0
1013    86.0
1014    88.0
Length: 1015, dtype: float64

### Yêu cầu 5:

**a. Tính giá trị BMI (Body Mass Index) của height_m và weight_kg và lưu vào bmi**

In [16]:
BMI = pd.Series(weight_kg/(height_m*height_m))

**b. In ra danh sách các phần tử của Series bmi**

In [17]:
BMI

0       23.200543
1       27.727478
2       28.367524
3       28.367524
4       24.835646
          ...    
1010    25.127831
1011    23.200543
1012    25.761773
1013    23.822715
1014    25.712199
Length: 1015, dtype: float64

### Yêu cầu 6:

**Cho biết giá trị cân nặng của VĐV ở vị trí index = 50 trong weight_kg**

In [18]:
weight_kg[50]

91.0

### Yêu cầu 7:

**Lọc ra chiều cao của các VĐV ở vị trí index từ 100 đến 110 (lấy cả index 110) trong height_m**

In [19]:
height_m[100:111]

100    1.85
101    1.88
102    1.83
103    1.85
104    1.75
105    1.83
106    1.85
107    1.90
108    1.90
109    1.85
110    1.83
dtype: float64

### Yêu cầu 8:

**a. Tạo và in kết quả của biểu thức điều kiện dùng để lấy ra các cầu thủ bóng chày có bmi < 21**

In [20]:
light = BMI < 21
light

0       False
1       False
2       False
3       False
4       False
        ...  
1010    False
1011    False
1012    False
1013    False
1014    False
Length: 1015, dtype: bool

**b. Áp dụng biểu thức điều kiện để in ra các cầu thủ bóng chày có bmi < 21 trong bmi**

In [21]:
BMI_LowerThan_21 = BMI[light]
BMI_LowerThan_21

13     20.654142
89     20.654142
159    20.671696
271    20.671696
279    20.305175
357    20.305175
499    20.671696
658    20.043732
742    19.667590
793    20.671696
906    20.987654
dtype: float64

### Yêu cầu 9:

**Cho biết chiều cao và cân nặng trung bình của các VĐV**

In [22]:
AverageHeight = round(height_m.mean(),2)
print('Chiều cao trung bình của các VĐV là: ', AverageHeight, 'm')
AverageWeight = round(weight_kg.mean(),2)
print('Cân nặng trung bình của các VĐV là: ', AverageWeight, 'kg')

Chiều cao trung bình của các VĐV là:  1.87 m
Cân nặng trung bình của các VĐV là:  91.35 kg


### Yêu cầu 10:

**a.Cho biết mức chiều cao và cân nặng có nhiều VĐV nhất**

In [23]:
ModeHeight = height_m.mode().to_string(index = False, dtype = False)
print('Mức chiều cao mà nhiều VĐV sở hữu là: ', ModeHeight, 'm')
ModeWeight = weight_kg.mode().to_string(index = False, dtype = False)
print('Mức cân nặng mà nhiều VĐV sở hữu nhất là: ', ModeWeight, 'kg')

Mức chiều cao mà nhiều VĐV sở hữu là:  1.88 m
Mức cân nặng mà nhiều VĐV sở hữu nhất là:  91.0 kg


**b. Đếm số VĐV theo chiều cao**

In [24]:
CountByHeight = height_m.value_counts()
CountByHeight

1.88    173
1.85    162
1.90    155
1.83    150
1.93    101
1.80     89
1.96     55
1.78     51
1.98     27
1.75     19
2.01     14
1.73      7
2.03      5
2.06      2
2.08      2
1.70      2
2.11      1
Name: count, dtype: int64

**c. 10 mức cân nặng có nhiều VĐV nhất**

In [25]:
CountByWeight = weight_kg.sort_values().value_counts()
CountByWeight.head(10)

91.0     109
86.0     100
82.0      82
95.0      76
100.0     74
93.0      64
84.0      56
88.0      52
98.0      42
77.0      40
Name: count, dtype: int64

### Yêu cầu 11: 

**a. Cho biết chiều cao và cân nặng lớn nhất của các VĐV**

In [26]:
MaxHeight = height_m.max()
MaxWeight = weight_kg.max()
print('Chiều cao lớn nhất của các VĐV là: ', MaxHeight, 'm')
print('Cân nặng lớn nhất của các VĐV là: ', MaxWeight, 'kg')

Chiều cao lớn nhất của các VĐV là:  2.11 m
Cân nặng lớn nhất của các VĐV là:  132.0 kg


**b. Cho biết các cầu thủ có chiều cao lớn nhất. Vị trí index các cầu thủ có chiều cao lớn nhất. Chiều cao lớn nhất là bao nhiêu?**

In [27]:
IndexHeightMax = height_m.idxmax()
print('Vị trí cầu thủ có chiều cao lớn nhất trong Series là: ', IndexHeightMax)
print('Chiều cao lớn nhất là: ', MaxHeight, 'm')

Vị trí cầu thủ có chiều cao lớn nhất trong Series là:  909
Chiều cao lớn nhất là:  2.11 m


In [28]:
print('Vị trí cầu thủ có chiều cao lớn nhất trong Series là: ')
print(height_m.sort_values(ascending = False).head(1))
print('Chiều cao lớn nhất là: ', MaxHeight, 'm')

Vị trí cầu thủ có chiều cao lớn nhất trong Series là: 
909    2.11
dtype: float64
Chiều cao lớn nhất là:  2.11 m


**c. Cho biết có bao nhiêu VĐV cao từ 2m trở lên**

In [29]:
HigherThan2 = height_m[height_m > 2]
HigherThan2.count()

24

In [30]:
height_m[height_m > 2].count()

24

### Yêu cầu 12:

**Cho biết chiều cao và cân nặng nhỏ nhất của các VĐV**

In [31]:
print('Chiều cao thấp nhất của các VĐV: ', height_m.min(), 'm')
print('Cân nặng nhỏ nhất của các VĐV: ', weight_kg.min(), 'kg')

Chiều cao thấp nhất của các VĐV:  1.7 m
Cân nặng nhỏ nhất của các VĐV:  68.0 kg


### Yêu cầu 13:

**a. In ra chiều cao tăng dần**

In [32]:
print('Danh sách chiều cao tăng dần: ')
height_m.sort_values()

Danh sách chiều cao tăng dần: 


989    1.70
988    1.70
83     1.73
809    1.73
784    1.73
       ... 
59     2.06
764    2.06
862    2.08
558    2.08
909    2.11
Length: 1015, dtype: float64

**b. 5 VĐV thấp nhất**

In [33]:
print('5 VĐV thấp nhất là: ')
height_m.sort_values().head(5)

5 VĐV thấp nhất là: 


989    1.70
988    1.70
83     1.73
809    1.73
784    1.73
dtype: float64

### Yêu cầu 14:

**a. In ra chiều cao giảm dần**

In [34]:
print('Danh sách chiều cao giảm dần: ')
height_m.sort_values(ascending = False)

Danh sách chiều cao giảm dần: 


909    2.11
558    2.08
862    2.08
59     2.06
764    2.06
       ... 
809    1.73
756    1.73
953    1.73
988    1.70
989    1.70
Length: 1015, dtype: float64

**b. 5 VĐV cao nhất**

In [35]:
print('5 VĐV cao nhất là: ')
height_m.sort_values(ascending = False).head(5)

5 VĐV cao nhất là: 


909    2.11
558    2.08
862    2.08
59     2.06
764    2.06
dtype: float64

### Yêu cầu 15:

**a. Thống kê chung về cân nặng các VĐV**

In [36]:
weight_kg.describe()

count    1015.000000
mean       91.351724
std         9.447218
min        68.000000
25%        84.000000
50%        91.000000
75%        98.000000
max       132.000000
dtype: float64

**b. Thống kê chung về chiều cao các VĐV**

In [37]:
height_m.describe()

count    1015.000000
mean        1.870493
std         0.059047
min         1.700000
25%         1.830000
50%         1.880000
75%         1.900000
max         2.110000
dtype: float64

# CHAPTER 6 - EXCERCISE 2: DATAFRAME (NIFTY-50 STOCKS DATASET)

## Ghi chú về dữ liệu
**_It contains Stock Data for 50 of the Largest Indian Companies Listed on the NSE_**

**NIFTY 50** là chỉ số chuẩn của thị trường chứng khoán Ấn Độ đại diện cho mức bình quân gia quyền của 50 công ty Ấn Độ lớn nhất được niêm yết trên Sở Giao dịch Chứng khoán Quốc gia. Đây là một trong hai chỉ số chứng khoán chính được sử dụng ở Ấn Độ, chỉ số còn lại là **BSE SENSEX.**

**Nifty 50 được sở hữu và quản lý bởi NSE Indices.**

**_Dữ liệu ngày 26 tháng 11 năm 2021. Đây chỉ là dữ liệu thị trường trong một ngày cho các cổ phiếu NIFTY50._**
+ **Symbol:** A symbol or generally a ticker symbol is an abbreviation of a publicly traded share on stock market.
+ **Open:** It is the price of the first transaction of a business day.
+ **High:** It is the price of the highest transaction of a business day.
+ **Low:** It is the price of the lowest transaction of a business day.
+ **LTP:** LTP is the Last Traded Price of the stock.
+ **Chng:** Change in the stock price from the previous day close
    + % Chng = Percentage of change from the previous day close
+ **Volume:** The total number of shares traded in a specified time frame
+ **Turnover:** The amount of revenue generated annually.
+ **52w H:** The highest value of the stock in the last 52 weeks.
+ **52w L:** The lowest value of the stock in the last 52 weeks.
    + 365 d % chng = Stock price percentage change from one year
    + 30 d % chng = Stock price percentage change from last 30 days
 
Lý do cho sự khác biệt giữa **Close Price** và **Last Traded Price (LTP)** là **LTP** đại diện cho giá giao dịch cuối cùng thực tế, trong khi **Close Price** của **_NSE_** được tính bằng giá trị trung bình của 30 phút giao dịch cuối cùng.

Tại sao cổ phiếu không bắt đầu giao dịch ở mức **Close Price** của ngày hôm trước? Sau giờ làm việc, có những tin tức, biến động xảy ra làm thay đổi số tiền mà các nhà đầu tư sẵn sàng trả để sở hữu cổ phần của công ty và thay đổi giá cổ phiếu của công ty mà không có bất kỳ giao dịch nào xảy ra.

https://www1.nseindia.com/products/content/equities/equities/eq_security.htm 

+ Change: so với Prev Close (762.45) 
+ 365d % change: so với Close price của ngày 25/11/2020 (398.95)
+ 30d % change: so với Close price của ngày 26/10/2021 (749.90) (10/2021 có 31 ngày)

**_Số liệu minh họa là của mã CK 'ADANIPORTS'_**

In [68]:
import pandas as pd

### Yêu cầu 1:

**a. Đọc dữ liệu từ 'National_Stock_Exchange_of_India_Ltd.csv' vào dataframe stocks**

In [69]:
National_Stock_Exchange_of_India_Ltd = pd.read_csv('data6/National_Stock_Exchange_of_India_Ltd.csv')

**b. Hiển thị 5 dòng dữ liệu đầu tiên**

In [70]:
National_Stock_Exchange_of_India_Ltd.head(5)

Symbol       Open       High        Low        LTP    Chng  % Chng  \
0  ADANIPORTS        750        766     713.25        715  -47.45   -6.22   
1  ASIANPAINT   3,101.00   3,167.35   3,091.00   3,138.00   -6.25   -0.20   
2    AXISBANK        669      674.9     660.45        661  -18.90   -2.78   
3  BAJAJ-AUTO   3,370.00   3,383.50   3,320.00   3,335.00  -56.70   -1.67   
4  BAJAJFINSV  17,200.00  17,237.20  16,610.00  16,684.00 -684.85   -3.94   

   Volume (lacs) Turnover (crs.)      52w H     52w L  365 d % chng  \
0          72.20          532.63        901     384.4         79.22   
1          10.29          322.53   3,505.00  2,117.15         45.66   
2         102.53             684      866.9     568.4         10.19   
3           3.42          114.59   4,361.40  3,041.00          9.30   
4           3.42          576.79  19,325.00  8,273.70         91.38   

   30 d % chng  
0        -4.65  
1         5.66  
2       -21.49  
3       -12.05  
4        -9.10

**c. Hiển thị thông tin info của dataframe**

In [41]:
National_Stock_Exchange_of_India_Ltd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Symbol           50 non-null     object 
 1   Open             50 non-null     object 
 2   High             50 non-null     object 
 3   Low              50 non-null     object 
 4   LTP              50 non-null     object 
 5   Chng             50 non-null     float64
 6   % Chng           50 non-null     float64
 7   Volume (lacs)    50 non-null     float64
 8   Turnover (crs.)  50 non-null     object 
 9   52w H            50 non-null     object 
 10  52w L            50 non-null     object 
 11  365 d % chng     50 non-null     float64
 12  30 d % chng      50 non-null     float64
dtypes: float64(5), object(8)
memory usage: 5.2+ KB


### Yêu cầu 2:

**Chuyển đổi các cột Open, High, Low, LTP, Turnover (crs.), 52w H, 52w L về kiểu dữ liệu float**

In [71]:
National_Stock_Exchange_of_India_Ltd['Turnover (crs.)'] = National_Stock_Exchange_of_India_Ltd['Turnover (crs.)'].str.replace(',', '').astype(float)

In [72]:
columns_to_convert = ['Open', 'High', 'Low', 'LTP', '52w H', '52w L']
for i in columns_to_convert:
    National_Stock_Exchange_of_India_Ltd[i] = National_Stock_Exchange_of_India_Ltd[i].str.replace(',', '').astype(float)

### Yêu cầu 3:

**a. Đổi tên các cột % Chng, Volume (lacs), Turnover (crs.), 52w H, 52w L, 365 d % chng, 30 d % chng thành 'Chng_pct', 'Volume_lacs', 'Turnover_crs', 'H_52w', 'L_52w', 'chng_365d_pct', 'chng_30d_pct'**

In [73]:
columns_change_name = {
    '% Chng': 'Chng_pct',
    'Volume (lacs)': 'Volume_lacs',
    'Turnover (crs.)': 'Turnover_crs',
    '52w H': 'H_52w',
    '52w L': 'L_52w',
    '365 d % chng': 'chng_365d_pct',
    '30 d % chng': 'chng_30d_pct'
}
National_Stock_Exchange_of_India_Ltd.rename(columns = columns_change_name, inplace = True)
    

**b. Hiển thị lại 5 dòng dữ liệu đầu tiên**

In [74]:
National_Stock_Exchange_of_India_Ltd.head(5)

Symbol     Open      High       Low      LTP    Chng  Chng_pct  \
0  ADANIPORTS    750.0    766.00    713.25    715.0  -47.45     -6.22   
1  ASIANPAINT   3101.0   3167.35   3091.00   3138.0   -6.25     -0.20   
2    AXISBANK    669.0    674.90    660.45    661.0  -18.90     -2.78   
3  BAJAJ-AUTO   3370.0   3383.50   3320.00   3335.0  -56.70     -1.67   
4  BAJAJFINSV  17200.0  17237.20  16610.00  16684.0 -684.85     -3.94   

   Volume_lacs  Turnover_crs    H_52w    L_52w  chng_365d_pct  chng_30d_pct  
0        72.20        532.63    901.0   384.40          79.22         -4.65  
1        10.29        322.53   3505.0  2117.15          45.66          5.66  
2       102.53        684.00    866.9   568.40          10.19        -21.49  
3         3.42        114.59   4361.4  3041.00           9.30        -12.05  
4         3.42        576.79  19325.0  8273.70          91.38         -9.10

### Yêu cầu 4:

**Hiển thị thông tin thống kê chung của stocks**

In [75]:
National_Stock_Exchange_of_India_Ltd.describe()

Open          High           Low           LTP        Chng  \
count     50.000000     50.000000     50.000000     50.000000   50.000000   
mean    2985.739000   3017.261000   2914.208000   2939.569000  -70.133000   
std     5024.412163   5057.739037   4911.417131   4943.921262  163.203678   
min      125.600000    125.600000    120.500000    121.150000 -770.500000   
25%      673.000000    678.425000    662.112500    663.187500  -66.775000   
50%     1155.950000   1156.750000   1105.750000   1121.250000  -29.975000   
75%     2760.262500   2789.425000   2668.537500   2690.450000   -7.812500   
max    26450.000000  26539.900000  25812.000000  25900.000000  158.400000   

        Chng_pct  Volume_lacs  Turnover_crs         H_52w         L_52w  \
count  50.000000    50.000000     50.000000     50.000000     50.000000   
mean   -2.930200    71.266600    569.706800   3440.588000   2208.556800   
std     2.677007    93.462062    492.383108   5813.045344   3962.991087   
min    -7.480000     0.300000     76.940000    141.500000     77.050000   
25%    -4.527500    13.472500    195.897500    777.825000    391.837500   
50%    -3.300000    30.750000    463.430000   1456.125000    819.775000   
75%    -1.932500    99.200000    744.502500   3388.000000   2272.600000   
max     7.230000   517.880000   2430.360000  32048.000000  22531.000000   

       chng_365d_pct  chng_30d_pct  
count      50.000000     50.000000  
mean       41.203000     -5.996800  
std        37.358646      6.322546  
min       -16.020000    -22.080000  
25%         9.375000     -9.665000  
50%        35.860000     -5.705000  
75%        65.942500     -2.222500  
max       167.950000      6.360000

### Yêu cầu 5:

**Lấy ra thông tin các mã cổ phiếu của ngân hàng (Symbol chứa 'BANK')**

In [76]:
StockIDBank = National_Stock_Exchange_of_India_Ltd[National_Stock_Exchange_of_India_Ltd['Symbol'].str.contains('BANK')]
StockIDBank

Symbol    Open     High      Low      LTP   Chng  Chng_pct  \
2    AXISBANK   669.0   674.90   660.45   661.00 -18.90     -2.78   
17   HDFCBANK  1500.0  1506.70  1485.00  1489.50 -36.45     -2.39   
22  ICICIBANK   739.0   742.05   718.60   720.45 -30.60     -4.07   
28  KOTAKBANK  2002.0  2007.00  1955.10  1960.00 -75.10     -3.69   

    Volume_lacs  Turnover_crs   H_52w   L_52w  chng_365d_pct  chng_30d_pct  
2        102.53        684.00   866.9   568.4          10.19        -21.49  
17        93.12       1394.10  1725.0  1342.0           6.18         -9.88  
22       189.88       1385.86   867.0   465.8          52.41        -13.14  
28        26.48        522.52  2253.0  1626.0           5.24        -11.35

### Yêu cầu 6:

**Lấy ra thông tin các mã cổ phiếu: 'CIPLA', 'HINDALCO', 'MARUTI', 'SHREECEM', 'WIPRO'**


In [77]:
National_Stock_Exchange_of_India_Ltd[National_Stock_Exchange_of_India_Ltd.Symbol.isin(['CIPLA','HINDALCO','MARUTI','SHREECEM','WIPRO'])]

Symbol     Open      High       Low      LTP    Chng  Chng_pct  \
9      CIPLA    892.0    976.05    890.65    965.0   65.05      7.23   
20  HINDALCO    441.8    442.70    414.70    417.7  -29.35     -6.57   
31    MARUTI   7520.0   7520.00   7130.00   7150.0 -422.50     -5.58   
39  SHREECEM  26450.0  26539.90  25812.00  25900.0 -770.50     -2.89   
49     WIPRO    632.0    634.40    619.65    621.3  -15.40     -2.42   

    Volume_lacs  Turnover_crs     H_52w     L_52w  chng_365d_pct  chng_30d_pct  
9        144.59       1380.90   1005.00    726.50          31.89          6.34  
20       148.26        631.93    551.85    220.35          86.93        -14.06  
31        11.55        840.81   8368.00   6400.00           1.34         -2.02  
39         0.30         76.94  32048.00  22531.00           9.29         -6.76  
49        41.39        259.37    739.85    346.25          77.51         -7.01

### Yêu cầu 7:

**Cho biết giá cao nhất trong năm của mã CP 'DIVISLAB'**

In [82]:
# Lọc ra thông tin của mã cổ phiếu 'DIVISLAB'
divislab_info = National_Stock_Exchange_of_India_Ltd[National_Stock_Exchange_of_India_Ltd['Symbol'] == 'DIVISLAB']
divislab_info

# Truy xuất giá cổ phiếu cao nhất trong cột 'H_52w' của mã cổ phiếu 'DIVISLAB'
max_price = divislab_info['H_52w'].max()

# In giá cổ phiếu cao nhất của mã cổ phiếu 'DIVISLAB'
print("Giá cổ phiếu cao nhất của mã cổ phiếu 'DIVISLAB' là:", max_price)


Giá cổ phiếu cao nhất của mã cổ phiếu 'DIVISLAB' là: 5425.1


### Yêu cầu 8:

**Mã CP có High cao nhất**

In [94]:
CodeHighMax = National_Stock_Exchange_of_India_Ltd[National_Stock_Exchange_of_India_Ltd['High'] == National_Stock_Exchange_of_India_Ltd['High'].max()]
CodeHighMax

Symbol     Open     High      Low      LTP   Chng  Chng_pct  \
39  SHREECEM  26450.0  26539.9  25812.0  25900.0 -770.5     -2.89   

    Volume_lacs  Turnover_crs    H_52w    L_52w  chng_365d_pct  chng_30d_pct  
39          0.3         76.94  32048.0  22531.0           9.29         -6.76

### Yêu cầu 9:

**Mã CP có Low thấp nhất**

In [88]:
CodeLowMin = National_Stock_Exchange_of_India_Ltd[National_Stock_Exchange_of_India_Ltd['Low'] == National_Stock_Exchange_of_India_Ltd['Low'].min()]
CodeLowMin

Symbol   Open   High    Low     LTP  Chng  Chng_pct  Volume_lacs  \
25    IOC  125.6  125.6  120.5  121.15  -4.5     -3.58        77.25   

    Turnover_crs  H_52w  L_52w  chng_365d_pct  chng_30d_pct  
25         94.57  141.5   84.0          41.28         -7.87

### Yêu cầu 10:

**Mã cổ phiếu có LTP lớn hơn giá mở cửa Open**

In [89]:
LTPHigherThanOpen = National_Stock_Exchange_of_India_Ltd[National_Stock_Exchange_of_India_Ltd['LTP'] > National_Stock_Exchange_of_India_Ltd['Open']]
LTPHigherThanOpen

Symbol      Open      High       Low      LTP    Chng  Chng_pct  \
1   ASIANPAINT   3101.00   3167.35   3091.00   3138.0   -6.25     -0.20   
8    BRITANNIA   3560.00   3635.10   3533.95   3566.6   -6.80     -0.19   
9        CIPLA    892.00    976.05    890.65    965.0   65.05      7.23   
11    DIVISLAB   4770.00   5077.70   4756.75   4940.0  140.20      2.92   
12     DRREDDY   4580.00   4820.00   4576.15   4750.0  158.40      3.45   
32   NESTLEIND  19148.85  19434.10  18982.50  19250.0   71.95      0.38   
44         TCS   3425.00   3490.00   3411.90   3439.2   -6.70     -0.19   

    Volume_lacs  Turnover_crs     H_52w     L_52w  chng_365d_pct  chng_30d_pct  
1         10.29        322.53   3505.00   2117.15          45.66          5.66  
8          3.73        133.23   4153.00   3317.30           0.30         -3.42  
9        144.59       1380.90   1005.00    726.50          31.89          6.34  
11        15.71        775.37   5425.10   3153.30          42.39         -1.57  
12        10.72        508.97   5614.60   4135.00          -1.17          1.80  
32         0.56        108.61  20609.15  16002.10           9.87          0.17  
44        19.41        670.58   3989.90   2624.45          27.32         -1.25

### Yêu cầu 11:

**Thông tin thống kê chung về 'Chng_pct'**

In [93]:
DescribeChng_pct = National_Stock_Exchange_of_India_Ltd['Chng_pct'].describe()
DescribeChng_pct

count    50.000000
mean     -2.930200
std       2.677007
min      -7.480000
25%      -4.527500
50%      -3.300000
75%      -1.932500
max       7.230000
Name: Chng_pct, dtype: float64

### Yêu cầu 12:

**Các mã cổ phiếu tăng giá so với ngày hôm trước, sắp xếp giảm dần theo Chng_pct**

In [100]:
# Mã cổ phiếu tăng giá so với ngày hôm trước => Chng_pct > 0
Chng_pctIsPositive = National_Stock_Exchange_of_India_Ltd[National_Stock_Exchange_of_India_Ltd['Chng_pct'] > 0]
Chng_pctIsPositive.sort_values(by = 'Chng_pct', ascending = False)

Symbol      Open      High       Low      LTP    Chng  Chng_pct  \
9       CIPLA    892.00    976.05    890.65    965.0   65.05      7.23   
12    DRREDDY   4580.00   4820.00   4576.15   4750.0  158.40      3.45   
11   DIVISLAB   4770.00   5077.70   4756.75   4940.0  140.20      2.92   
32  NESTLEIND  19148.85  19434.10  18982.50  19250.0   71.95      0.38   

    Volume_lacs  Turnover_crs     H_52w    L_52w  chng_365d_pct  chng_30d_pct  
9        144.59       1380.90   1005.00    726.5          31.89          6.34  
12        10.72        508.97   5614.60   4135.0          -1.17          1.80  
11        15.71        775.37   5425.10   3153.3          42.39         -1.57  
32         0.56        108.61  20609.15  16002.1           9.87          0.17

### Yêu cầu 13:

**Mã cổ phiếu có tỷ lệ tăng giá cao nhất (so với ngày hôm trước)**

In [99]:
Chng_pctIsHighest = National_Stock_Exchange_of_India_Ltd[National_Stock_Exchange_of_India_Ltd['Chng_pct'] == National_Stock_Exchange_of_India_Ltd['Chng_pct'].max()]
Chng_pctIsHighest

Symbol   Open    High     Low    LTP   Chng  Chng_pct  Volume_lacs  \
9  CIPLA  892.0  976.05  890.65  965.0  65.05      7.23       144.59   

   Turnover_crs   H_52w  L_52w  chng_365d_pct  chng_30d_pct  
9        1380.9  1005.0  726.5          31.89          6.34

### Yêu cầu 14:

**Mã cổ phiếu có khối lượng giao dịch nhiều nhất**

In [116]:
StockVolumeMax = National_Stock_Exchange_of_India_Ltd[National_Stock_Exchange_of_India_Ltd['Volume_lacs'] == National_Stock_Exchange_of_India_Ltd['Volume_lacs'].max()]
StockVolumeMax

Symbol   Open    High    Low    LTP   Chng  Chng_pct  Volume_lacs  \
42  TATAMOTORS  486.0  486.75  458.0  459.4 -33.35     -6.77       517.88   

    Turnover_crs  H_52w  L_52w  chng_365d_pct  chng_30d_pct  
42       2430.36  536.7  156.7         167.95         -9.68

### Yêu cầu 15:

**a. Mã cổ phiếu có tổng tiền giao dịch nhiều nhất**

In [124]:
SumStockTurnover = National_Stock_Exchange_of_India_Ltd.groupby('Symbol')['Turnover_crs'].sum()
SumStockTurnover[SumStockTurnover == SumStockTurnover.max()]

Symbol
TATAMOTORS    2430.36
Name: Turnover_crs, dtype: float64

In [129]:
StockTurnoverMax = National_Stock_Exchange_of_India_Ltd[National_Stock_Exchange_of_India_Ltd['Turnover_crs'] == National_Stock_Exchange_of_India_Ltd['Turnover_crs'].max()]
StockTurnoverMax

Symbol   Open    High    Low    LTP   Chng  Chng_pct  Volume_lacs  \
42  TATAMOTORS  486.0  486.75  458.0  459.4 -33.35     -6.77       517.88   

    Turnover_crs  H_52w  L_52w  chng_365d_pct  chng_30d_pct  
42       2430.36  536.7  156.7         167.95         -9.68

**b. 5 mã cổ phiếu có tổng tiền giao dịch nhiều nhất**

In [125]:
SumStockTurnover.sort_values(ascending = False).head(5)

Symbol
TATAMOTORS    2430.36
RELIANCE      1770.19
HDFCBANK      1394.10
ICICIBANK     1385.86
CIPLA         1380.90
Name: Turnover_crs, dtype: float64

In [135]:
Top5TurnoverStock = National_Stock_Exchange_of_India_Ltd.sort_values(by = 'Turnover_crs', ascending = False).head(5)
Top5TurnoverStock

Symbol    Open     High      Low      LTP   Chng  Chng_pct  \
42  TATAMOTORS   486.0   486.75   458.00   459.40 -33.35     -6.77   
36    RELIANCE  2467.8  2477.60  2401.50  2405.10 -87.85     -3.52   
17    HDFCBANK  1500.0  1506.70  1485.00  1489.50 -36.45     -2.39   
22   ICICIBANK   739.0   742.05   718.60   720.45 -30.60     -4.07   
9        CIPLA   892.0   976.05   890.65   965.00  65.05      7.23   

    Volume_lacs  Turnover_crs    H_52w   L_52w  chng_365d_pct  chng_30d_pct  
42       517.88       2430.36   536.70   156.7         167.95         -9.68  
36        72.75       1770.19  2751.35  1830.0          23.48         -9.62  
17        93.12       1394.10  1725.00  1342.0           6.18         -9.88  
22       189.88       1385.86   867.00   465.8          52.41        -13.14  
9        144.59       1380.90  1005.00   726.5          31.89          6.34

### Yêu cầu 16:

**a. Mã cổ phiếu giảm giá so với năm trước (chng_365d_pct < 0)**

In [139]:
StockDropYearPast = National_Stock_Exchange_of_India_Ltd[National_Stock_Exchange_of_India_Ltd['chng_365d_pct'] < 0]
StockDropYearPast.sort_values(by = 'chng_365d_pct')

Symbol     Open    High      Low      LTP    Chng  Chng_pct  \
19  HEROMOTOCO  2580.00  2589.7  2505.15  2526.80  -67.90     -2.62   
13   EICHERMOT  2495.00  2506.1  2421.50  2440.75  -79.65     -3.16   
7         BPCL   397.15   397.2   375.00   377.40  -22.70     -5.67   
12     DRREDDY  4580.00  4820.0  4576.15  4750.00  158.40      3.45   

    Volume_lacs  Turnover_crs    H_52w    L_52w  chng_365d_pct  chng_30d_pct  
19         6.85        174.04  3629.05  2505.15         -16.02         -6.43  
13         5.55        136.56  3037.00  2303.70          -5.95         -5.77  
7        100.23        383.54   503.00   357.00          -1.22        -12.45  
12        10.72        508.97  5614.60  4135.00          -1.17          1.80

**b. mã cP tăng giá so với 30 ngày trước**

In [137]:
ChngIsPositive30daysPast = National_Stock_Exchange_of_India_Ltd[National_Stock_Exchange_of_India_Ltd['chng_30d_pct'] > 0]
ChngIsPositive30daysPast.sort_values(by = 'chng_30d_pct', ascending = False)

Symbol      Open      High       Low       LTP    Chng  Chng_pct  \
35   POWERGRID    204.05    204.95    200.80    202.50   -1.75     -0.86   
9        CIPLA    892.00    976.05    890.65    965.00   65.05      7.23   
6   BHARTIARTL    763.00    763.00    733.10    735.85  -29.30     -3.83   
1   ASIANPAINT   3101.00   3167.35   3091.00   3138.00   -6.25     -0.20   
12     DRREDDY   4580.00   4820.00   4576.15   4750.00  158.40      3.45   
47  ULTRACEMCO   7550.00   7599.00   7370.10   7398.45 -210.35     -2.76   
32   NESTLEIND  19148.85  19434.10  18982.50  19250.00   71.95      0.38   

    Volume_lacs  Turnover_crs     H_52w     L_52w  chng_365d_pct  chng_30d_pct  
35        96.11        195.09    209.95    136.88           3.69          6.36  
9        144.59       1380.90   1005.00    726.50          31.89          6.34  
6        111.43        830.06    781.80    454.11          58.55          5.70  
1         10.29        322.53   3505.00   2117.15          45.66          5.66  
12        10.72        508.97   5614.60   4135.00          -1.17          1.80  
47         2.66        198.32   8269.00   4770.00          53.50          1.78  
32         0.56        108.61  20609.15  16002.10           9.87          0.17

### Yêu cầu 17:

**a. Tạo cột 'volatility' thể hiện khoảng biến động của giá CP trong 1 năm**

In [148]:
National_Stock_Exchange_of_India_Ltd['volatility'] = National_Stock_Exchange_of_India_Ltd['H_52w'] - National_Stock_Exchange_of_India_Ltd['L_52w']

**b. 5 mã CP biến động nhiều nhất**

In [147]:
National_Stock_Exchange_of_India_Ltd.sort_values(by = 'volatility', ascending = False).head(5)

Symbol      Open     High      Low       LTP    Chng  Chng_pct  \
4   BAJAJFINSV  17200.00  17237.2  16610.0  16684.00 -684.85     -3.94   
39    SHREECEM  26450.00  26539.9  25812.0  25900.00 -770.50     -2.89   
32   NESTLEIND  19148.85  19434.1  18982.5  19250.00   71.95      0.38   
5   BAJFINANCE   7021.00   7047.9   6775.0   6780.00 -345.80     -4.85   
47  ULTRACEMCO   7550.00   7599.0   7370.1   7398.45 -210.35     -2.76   

    Volume_lacs  Turnover_crs     H_52w    L_52w  chng_365d_pct  chng_30d_pct  \
4          3.42        576.79  19325.00   8273.7          91.38         -9.10   
39         0.30         76.94  32048.00  22531.0           9.29         -6.76   
32         0.56        108.61  20609.15  16002.1           9.87          0.17   
5         16.89       1161.63   8050.00   4362.0          44.57        -13.69   
47         2.66        198.32   8269.00   4770.0          53.50          1.78   

    volatility  
4     11051.30  
39     9517.00  
32     4607.05  
5      3688.00  
47     3499.00

### Yêu cầu 18:

**Tạo dataframe top_5_High là 5 mã CP có High cao nhất, chỉ lấy các cột Symbol, Open, High, Low**

In [151]:
top_5_High = National_Stock_Exchange_of_India_Ltd[['Symbol', 'Open', 'High', 'Low']].sort_values(by = 'High', ascending = False).head(5)
top_5_High

Symbol      Open     High      Low
39    SHREECEM  26450.00  26539.9  25812.0
32   NESTLEIND  19148.85  19434.1  18982.5
4   BAJAJFINSV  17200.00  17237.2  16610.0
47  ULTRACEMCO   7550.00   7599.0   7370.1
31      MARUTI   7520.00   7520.0   7130.0

### Yêu cầu 19:

**Hiển thị thông tin giá cao nhất, giá thấp nhất trong ngày của các mã CP theo mẫu:**
+ [Symbol] có giá cao nhất trong ngày là [High] và giá thấp nhất trong ngày là [Low]

In [152]:
print('5 mã CP có High cao nhất trong ngày 26/11/2021:')
for index, row in top_5_High.iterrows():
    print("Mã CP:", row['Symbol'])
    print("Giá mở cửa:", row['Open'])
    print("Giá cao nhất:", row['High'])
    print("Giá thấp nhất:", row['Low'])
    print()

5 mã CP có High cao nhất trong ngày 26/11/2021:
Mã CP: SHREECEM
Giá mở cửa: 26450.0
Giá cao nhất: 26539.9
Giá thấp nhất: 25812.0

Mã CP: NESTLEIND
Giá mở cửa: 19148.85
Giá cao nhất: 19434.1
Giá thấp nhất: 18982.5

Mã CP: BAJAJFINSV
Giá mở cửa: 17200.0
Giá cao nhất: 17237.2
Giá thấp nhất: 16610.0

Mã CP: ULTRACEMCO
Giá mở cửa: 7550.0
Giá cao nhất: 7599.0
Giá thấp nhất: 7370.1

Mã CP: MARUTI
Giá mở cửa: 7520.0
Giá cao nhất: 7520.0
Giá thấp nhất: 7130.0



# CHAPTER 6 - EXCERCISE 3: COMBINING DATA (IllINOIS MALE BABY NAMES)

## Ghi chú về dữ liệu

+ Cho dữ liệu 201*-baby-names-illinois.csv. 
+ Bộ dữ liệu này thống kê tần suất các tên gọi được đặt.
+ Dữ liệu được lưu tại nhiều files
+ Tên files 201-baby-names-illinois.csv chứa 201 là năm tương ứng

**Yêu cầu:**
+ Hãy tạo thêm cột year là 4 ký tự đầu tiên của tên file
+ Kết hợp dữ liệu thành 1 dataframe hoàn chỉnh.

In [1]:
import pandas as pd
import glob

In [2]:
allFiles = glob.glob("data6/201*-baby-names-illinois.csv")
frame = pd.DataFrame()
df_list= []
for file_ in allFiles:
    df = pd.read_csv(file_,index_col=None)
    print(file_, df.shape)
    df.columns = map(str.lower, df.columns)
    df["year"] = file_[5:9]
    df_list.append(df)

data6\2014-baby-names-illinois.csv (101, 4)
data6\2015-baby-names-illinois.csv (100, 4)


In [5]:
df4 = pd.concat(df_list)
df4.head(5)

rank       name  frequency   sex  year
0     1       Noah        837  Male  \201
1     2  Alexander        747  Male  \201
2     3    William        687  Male  \201
3     4    Michael        680  Male  \201
4     5       Liam        670  Male  \201

In [4]:
df4.shape

(201, 5)

# CHAPTER 6 - EXERCISE 4: COMBINING DATA

In [8]:
import pandas as pd
import glob

### Yêu cầu 1: Cho dữ liệu employees1.csv và employees2.csv

**a. Đọc dữ liệu từ 2 tập tin trên**

In [7]:
emp1 = pd.read_csv('data6/employees1.csv', index_col = 0)
emp2 = pd.read_csv('data6/employees2.csv', index_col = 0)

In [9]:
emp1

employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
4     John           IT
5    Billy           HR

In [10]:
emp2

employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014
4     John       2010
5    Billy       2015

**b. Kết hợp 2 dữ liệu trên thành 1 DataFrame**

In [22]:
employees = pd.merge(emp1, emp2)
employees

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014
4     John           IT       2010
5    Billy           HR       2015

### Yêu cầu 2: Cho dữ liệu department.csv

**a. Đọc dữ liệu từ tập tin trên**

In [24]:
department = pd.read_csv('data6/department.csv', index_col = 0)
department

group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve
3           IT       Jame

**b. Kết hợp dữ liệu này với dữ liệu kết quả từ câu 1**

In [25]:
employeesdepartment = pd.merge(emp1emp2, department)
employeesdepartment

employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve
4     John           IT       2010       Jame
5    Billy           HR       2015      Steve

### Yêu cầu 3: Cho dữ liệu skills.csv

**a. Đọc dữ liệu từ tập tin trên**

In [26]:
skills = pd.read_csv('data6/skills.csv', index_col = 0)
skills

group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization
6           IT        coding
7           IT          math

**b. Kết hợp dữ liệu này với dữ liệu kết quả từ câu 2**

In [27]:
employeesdepartmentskills = pd.merge(emp1emp2department, skills)
employeesdepartmentskills

employee        group  hire_date supervisor        skills
0       Bob   Accounting       2008      Carly          math
1       Bob   Accounting       2008      Carly  spreadsheets
2      Jake  Engineering       2012      Guido        coding
3      Jake  Engineering       2012      Guido         linux
4      Lisa  Engineering       2004      Guido        coding
5      Lisa  Engineering       2004      Guido         linux
6       Sue           HR       2014      Steve  spreadsheets
7       Sue           HR       2014      Steve  organization
8      John           IT       2010       Jame        coding
9      John           IT       2010       Jame          math
10    Billy           HR       2015      Steve  spreadsheets
11    Billy           HR       2015      Steve  organization

### Yêu cầu 4: Cho dữ liệu salary.csv

**a. Đọc dữ liệu từ tập tin trên**

In [28]:
salary = pd.read_csv('data6/salary.csv', index_col = 0)
salary

name  salary
0    Bob   70000
1   Jake   80000
2   Lisa  120000
3    Sue   90000
4   John  125000
5  Billy   92000

**b. Kết hợp dữ liệu này với dữ liệu ở câu 1**

**Gợi ý:** dùng right_on & left_on khi merge vì trong salary không có cột name, còn df ở câu 1 lại có cột employee trùng nội dung, bỏ cột name)

In [34]:
employeessalary = pd.merge(employees, salary, right_on = 'name', left_on = 'employee')
employeessalary.drop('name', axis = 1)

employee        group  hire_date  salary
0      Bob   Accounting       2008   70000
1     Jake  Engineering       2012   80000
2     Lisa  Engineering       2004  120000
3      Sue           HR       2014   90000
4     John           IT       2010  125000
5    Billy           HR       2015   92000

### Yêu cầu 5: Cho dữ liệu như sau:

**1. df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'], 'food': ['fish', 'beans', 'bread']}, columns=['name', 'food'])**

**2. df7 = pd.DataFrame({'name': ['Mary', 'Joseph'], 'drink': ['wine', 'beer']}, columns=['name', 'drink'])**
    
- Kết hợp 2 bộ dữ liệu này với tham số how='inner', how='outer', how='left', how='right'. Quan sát kết quả trong từng trường hợp.

In [35]:
df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'], 
                    'food': ['fish', 'beans', 'bread']}, 
                    columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'], 
                    'drink': ['wine', 'beer']}, 
                    columns=['name', 'drink'])

In [36]:
display(df6, df7)

name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread

name drink
0    Mary  wine
1  Joseph  beer

In [38]:
df67_merge = pd.merge(df6, df7)
df67_merge

name   food drink
0  Mary  bread  wine

In [39]:
df67_inner = pd.merge(df6, df7, how = 'inner')
df67_inner

name   food drink
0  Mary  bread  wine

In [40]:
df67_left = pd.merge(df6, df7, how = 'left')
df67_left

name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine

In [41]:
df67_right = pd.merge(df6, df7, how = 'right')
df67_right

name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer

In [42]:
df67_outer = pd.merge(df6, df7, how = 'outer')
df67_outer

name   food drink
0  Joseph    NaN  beer
1    Mary  bread  wine
2    Paul  beans   NaN
3   Peter   fish   NaN

### Yêu cầu 1+: Cho dữ liệu employees1.csv và employees2.csv

**a. Đọc dữ liệu từ 2 tập tin trên vào 2 DataFrame với index của các DataFrame là 'employee'**

In [71]:
employees1 = pd.read_csv('data6/employees1.csv', index_col = 'employee')
employees2 = pd.read_csv('data6/employees2.csv', index_col = 'employee')

In [72]:
employees1.drop(employees1.columns[0], axis = 1, inplace = True)
employees1

group
employee             
Bob        Accounting
Jake      Engineering
Lisa      Engineering
Sue                HR
John               IT
Billy              HR

In [73]:
employees2.drop(employees2.columns[0], axis = 1, inplace = True)
employees2

hire_date
employee           
Lisa           2004
Bob            2008
Jake           2012
Sue            2014
John           2010
Billy          2015

**b. Kết hợp 2 DataFrame trên thành 1 DataFrame dùng chung 1 index là 'employee' (gợi ý: dùng left_index hoặc/và right_index hoặc dùng dataframe1.join(dataframe2))**

In [76]:
employees12_merge = pd.merge(employees1, employees2, right_index = True, left_index = True)
employees12_merge

group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014
John               IT       2010
Billy              HR       2015

In [78]:
employees_join = employees1.join(employees2)
employees_join

group  hire_date
employee                        
Bob        Accounting       2008
Jake      Engineering       2012
Lisa      Engineering       2004
Sue                HR       2014
John               IT       2010
Billy              HR       2015